-- lvim-icons.data.svg: the svg-mode (COLRv1) ligature overlay, keyed by icon `name`.
-- GENERATED by the font build pipeline (assets/, a later phase) — do NOT hand-edit. Each
-- entry is `{ seq = { <codepoints> }, variants = { soft = {…}, dark = {…}, darker = {…},
-- light = {…} } }`: the base emoji + Unicode variation selectors the terminal shapes into the
-- coloured vector glyph, one sequence set per lvim-colorscheme brightness variant.
--
-- Empty until the font ships: with no entry for an icon, svg mode falls back to that icon's
-- Nerd Font glyph per-icon (see svg.sequence / resolve.lua), so the plugin is fully usable in
-- font mode today and svg mode lights up incrementally as entries land.
--
---@module "lvim-icons.data.svg"

---@class LvimIconSvgEntry
---@field seq      integer[]                     Base ligature sequence (variant-agnostic fallback)
---@field variants table<string, integer[]>?     Per-variant sequences (soft/dark/darker/light)

---@type table<string, LvimIconSvgEntry>
return {}
